### PR TITLE
expense ui improvement

### PR DESCRIPTION
**Pull request by ivangarcilazo**
Ui improve

### CODE REVIEW

**Review by bharathkumarchowdary — CHANGES_REQUESTED** [review]
Homepage has the charts of expenses.. need to move those 3 charts to expense page

**Comment by ivangarcilazo** [comment]
Oh okay, so it would be to remove the expense graphs from the home page and put them on the expense page as the 4 budgets at the top of the expense list, right?

**Comment by bharathkumarchowdary** [comment]
In the Figma page, I put the 3 charts in their respective places.. after moving them to expenses page, they're no more needed in the home page

**Comment by mohitkhatri06** [comment]
whenever we add a new expense then its showing an error before.
image

Apart from that if you try to add the new expense with "Test5" credentials then page also breaks.

**Comment by bharathkumarchowdary** [comment]
> whenever we add a new expense then its showing an error before. image
> 
> Apart from that if you try to add the new expense with "Test5" credentials then page also breaks.

If it breaks with specific credentials, @Edu58  should have a look at it

**Comment by ivangarcilazo** [comment]
Mohit! There I managed to solve the problem that arose, regarding the credentials, once the problem was solved, I changed the credentials and no error has been presented, nor has the page been broken.

**Comment by mohitkhatri06** [comment]
if you try to add the new expense with "Test5" credentials then page also breaks. 

image

**Comment by Edu58** [comment]
> whenever we add a new expense then its showing an error before. image
> 
> Apart from that if you try to add the new expense with "Test5" credentials then page also breaks.

I think this is okay. It means on the first request the token used had expired as we can see from the 401 status code, and so it got a new token from the backend and sent the request again.

**Comment by ivangarcilazo** [comment]
Hi! I tested by myself and the features that i added fixed that problem.

**Review by mohitkhatri06 — APPROVED** [review]

**Review by mohitkhatri06 — DISMISSED** [review]

**Comment by mohitkhatri06** [comment]
In ts migration and styling centralization this issue can be taken in care.

**Pull request closed without merging**
