### PR TITLE
refactor(router): move calculators outside protected routes 

### PR DESCRIPTION
**Pull request by rockingrohit9639**
I have moved all three of the calculators outside authenticated routes, now these can be accessible publically.

Fix - #171 

Here is a screenshot of what it looks like.
image

image

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205553768553279

### CODE REVIEW

**Comment by mohitkhatri06** [comment]
@ivangarcilazo Have a look on the following for me all looks working

**Comment by ivangarcilazo** [comment]
Let me check

**Comment by ivangarcilazo** [comment]
I think the same Mohit! Looks good

**Review by ivangarcilazo — APPROVED** [review]

**Review by mohitkhatri06 — DISMISSED** [review]

**Comment by mohitkhatri06** [comment]
@Edu58 please review the following changes so we can proceed.

**Comment by bharathkumarchowdary** [comment]
@rockingrohit9639 , there are conflicts on this branch. Please rebase to master

**Comment by rockingrohit9639** [comment]
> @rockingrohit9639 , there are conflicts on this branch. Please rebase to master

Done

**Comment by bharathkumarchowdary** [comment]
Still Conflicts!

**Review by mohitkhatri06 — APPROVED** [review]

**Pull request merged**
