### PR TITLE
Display public scenario to unauthorized users.

### PR DESCRIPTION
**Pull request by Sandip-Z**
This PR addresses the issue #509.

- fix: public scenario not displaying for unauthorized user

### CODE REVIEW

**Comment by mohitkhatri06** [comment]
@Sandip-Z  one case is failing here
private scenario of the user A if I copy and try to open that link when I am logged in as B

**Comment by mohitkhatri06** [comment]
@Sandip-Z found one problem here when user A share his public scenario with the B then if B is logged in they are able to add one more assets or liablities to the A's scenario.

**Comment by mohitkhatri06** [comment]
@Sandip-Z  here I am feeling somthing is not correct, when I login as Mohit, and use the Sandip's http://localhost:3000/scenarios/42 url then it is taking me as Sandip even I can into your account, might be somthing related to token.

**Comment by bharathkumarchowdary** [comment]
> @Sandip-Z here I am feeling somthing is not correct, when I login as Mohit, and use the Sandip's http://localhost:3000/scenarios/42 url then it is taking me as Sandip even I can into your account, might be somthing related to token.

this looks like a security issue. @mohitkhatri06  can you please check that if this issue is persistent even if you use browser's incognito and raise an issue with steps to reproduce?

**Comment by mohitkhatri06** [comment]
@bharathkumarchowdary attaching one video for the reference

https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/78607953/6c8ef73a-2be7-4fec-91a4-7f75f139a8b3

**Comment by bharathkumarchowdary** [comment]
This is a security issue. We are not logging out correctly. if the tokens are destroyed, there is no way the frontend should be able to login with that user

**Comment by bharathkumarchowdary** [comment]
@Sandip-Z , there are conflicts to resolve in this

**Review by bharathkumarchowdary — APPROVED** [review]

**Pull request merged**
