### PR TITLE
navBar redesigned

### PR DESCRIPTION
**Pull request by BeteabAdmassu**
image
image

### CODE REVIEW

**Comment by mohitkhatri06** [comment]
let us know when the PR is ready for review.

**Comment by BeteabAdmassu** [comment]
I have redesigned the navbar and is ready for review. Your feedback is appreciated.

**Comment by mohitkhatri06** [comment]
1.  when we change screen size it shows 2 menu options
image

2. Lets add the respective pages link to the navButtons
3. Add some highlight or isActive style to a button, so user gets an idea in page he/she is

**Comment by ivangarcilazo** [comment]
Ajuste header

I agree with Mohit, it looks good! One thing I can add is that in the resolution 600px to 800px just add a little distance with a gap:.25 rem; for example, but it looks good.

**Comment by BeteabAdmassu** [comment]
I've made the following fixes in this pull request:

1. Resolved the screen size issue, so the menu now displays correctly.
2. Added respective page links to the navButtons.
3. Included a highlight/isActive style for buttons to improve user navigation.
4. Reduced the Navbar height slightly.
5. Added gap between the buttons for smaller devices

Ready for review

**Comment by mohitkhatri06** [comment]
Thanks Beteab you are doing good just few little more suggestions:
1. in mobile view we can add those "profile", ... ,"logout" as a drop down or submenu as for now we don't have logout for mobile view.
2.  add tool tip for the icons 
3.  invert the isActive color for icon, as for now it is black for active just invert it

**Comment by mohitkhatri06** [comment]
as for now logout functionality is not working, and iconButton: {
    width: "49px", 
    height: "51px",
   ...
  },
lets make it round by equal width and height

**Comment by BeteabAdmassu** [comment]
I've made the following fixes in this pull request:

1. Logout functionality is now working correctly.
2. The icon button is now round with equal width and height.

**Review by mohitkhatri06 — APPROVED** [review]

**Review by Edu58 — APPROVED** [review]

**Review by ivangarcilazo — APPROVED** [review]

**Review by bharathkumarchowdary — APPROVED** [review]

**Pull request merged**
