### PR TITLE
Calculator-icon-added

### PR DESCRIPTION
**Pull request by BeteabAdmassu**
Dropdown issue resolved: Added icon for calculator selection, click to open/close dropdown.

### CODE REVIEW

**Comment by BeteabAdmassu** [comment]
Ready for review.

**Comment by ivangarcilazo** [comment]
Looks good, can you add the links? 👍

**Comment by BeteabAdmassu** [comment]
I've added links to the submenus of the calculator.

**Comment by BeteabAdmassu** [comment]
Ready for review.

**Review by mohitkhatri06 — APPROVED** [review]

**Pull request merged**
