### PR TITLE
171 keep calculators out of authentication

### PR DESCRIPTION
**Pull request by Edu58**

### CODE REVIEW

**Comment by bharathkumarchowdary** [comment]
@Edu58 ,

Does the signin/signup ui looks like the new figma designs received?

**Comment by Edu58** [comment]
Not yet. I will do it in another branch

**Comment by mohitkhatri06** [comment]
@bharathkumarchowdary  should we hide remaining options? like Expenses and income statemnt.

image

**Comment by bharathkumarchowdary** [comment]
> @bharathkumarchowdary should we hide remaining options? like Expenses and income statemnt.
> 
> image

Yes Mohit… Thanks for pointing out 
Unauthenticated user should not see those options

**Pull request closed without merging**
