### PR TITLE
issue 245 : Add a card view or widget for budget at home screen

### PR DESCRIPTION
**Pull request by chahat151**

### CODE REVIEW

**Comment by bharathkumarchowdary** [comment]
looks good! but I have some comments

- budgets are per month. This week, last week are invalid options
- Have a look at budgets API and integrate this with those endpoints
- Spent needs to be green, left needs to be red (not absolute colours but any shades of those colours that suit our site are also fine)

@mohitkhatri06 
Do you need backend support to implement any functionality for this?

**Comment by mohitkhatri06** [comment]
@bharathkumarchowdary we have "Need create, edit, update, delete options for each month budget" this in expense section where user can do the actions.

should we follow these point after the merge of ts-migration?

**Comment by mohitkhatri06** [comment]
right now the budget progress bar is not accurate, the spent and left is same and color of the bars is constant. Its not working as it was previously

**Comment by chahat151** [comment]
color is fixes. Budget was showing wrong because it was comming zero in the expense api. Now I'am taking budget from different api. I think that has solved the issue.

**Pull request closed without merging**
