### PR TITLE
feat/testLoginButton

### PR DESCRIPTION
**Pull request by ivangarcilazo**

### CODE REVIEW

**Comment by mohitkhatri06** [comment]
@ivangarcilazo  you are also getting this console error?
image

**Comment by ivangarcilazo** [comment]
Nup, but I was able to find solution for this testing problem. Apparently window.scrollTo wasn't defined on the test environment. Now I'll make the pull request

**Comment by mohitkhatri06** [comment]
and this console error also came now.

image

**Comment by ivangarcilazo** [comment]
Ok, what I did is a mock up of the Mui/material components, and then, the console warnings went away.

**Comment by mohitkhatri06** [comment]
it working good, for future we will add more test cases with some dummy test credentials.

**Review by mohitkhatri06 — APPROVED** [review]

**Pull request merged**
