### PR TITLE
38-tag-creation-in-expense-add-dialog

### PR DESCRIPTION
**Pull request by ivangarcilazo**

### CODE REVIEW

**Comment by mohitkhatri06** [comment]
Hi Ivan, in this tag component previously there were some warnings if you feel they are easy to correct then proceed with it. 
image

**Comment by ivangarcilazo** [comment]
Sure :)

**Comment by ivangarcilazo** [comment]
Done!

**Review by mohitkhatri06 — APPROVED** [review]

**Comment by mohitkhatri06** [comment]
approved

**Comment by mohitkhatri06** [comment]
@ivangarcilazo  I saw that when we does not enter any tag name then its breaking please look into this, 
image

**Comment by ivangarcilazo** [comment]
Hello, the problem persists or is it already approved? To perform the merge?

**Comment by mohitkhatri06** [comment]
Not yet ready for merge, as this error is problem persists and also if we keep tag as empty it is taking that also:

image

**Comment by ivangarcilazo** [comment]
Done!

**Comment by mohitkhatri06** [comment]
https://user-images.githubusercontent.com/78607953/236689329-48198dfe-96b1-4cc1-bb9c-bca470f0f561.mp4

**Comment by ivangarcilazo** [comment]
I am really sorry! I'll get right on it.

**Comment by mohitkhatri06** [comment]
No issues take your time :)

**Comment by mohitkhatri06** [comment]
First time suppose I tried to add Colors which is new Tag, its not adding into the list first time, but second time I am able to add that.

**Comment by ivangarcilazo** [comment]
There I was able to find the bug! It was something about asynchrony

**Review by mohitkhatri06 — APPROVED** [review]

**Pull request merged**
