### PR TITLE
2 user authentication

### PR DESCRIPTION
**Pull request by Edu58**

### CODE REVIEW

**Comment by bharathkumarchowdary** [comment]
It's better to have login/signup form as a popup instead of a full page
Similar to Leave your feedback button on homepage

**Comment by mohitkhatri06** [comment]
* when I used the reacter credentials or any correct credentials then after signin it breaks the following calls. 

image

This is happening because in Provider.js file we are checking in the local storage while you are saving the token in the cookies, and also in some calls we need to remove the hardcoded user name and password in the Provider.js

* Signout needs to be implemented.

**Comment by mohitkhatri06** [comment]
perfect @Edu58 just few little changes, in provider.js line number 67 and 105 we are hardcoding the username and password, just remove those and add "header" as we used in other calls. And if possible lets make that signout button working, as for now its not routing.

**Comment by Edu58** [comment]
@mohitkhatri06 
The username and password hard coding issue in Provider has been FIXED. Also the Sign-out button is working now.

**Comment by Edu58** [comment]
I am open to anyone's opinion about the sign-out functionality. As of now, how I have implemented it by clearing the JWT token from the state and the refresh token saved in the Cookie. This way the app will always redirect the user to the sign-in page as it won't have a token to send request with or a refresh token to get a new token with.

However, my issue is I'm not sure if we should also clear store on sign-out. Should the store be cleared on sign out and if so what is the best way to do so?

**Review by mohitkhatri06 — DISMISSED** [review]

**Review by bharathkumarchowdary — DISMISSED** [review]

**Comment by bharathkumarchowdary** [comment]
> I am open to anyone's opinion about the sign-out functionality. As of now, how I have implemented it by clearing the JWT token from the state and the refresh token saved in the Cookie. This way the app will always redirect the user to the sign-in page as it won't have a token to send request with or a refresh token to get a new token with.
> 
> However, my issue is I'm not sure if we should also clear store on sign-out. Should the store be cleared on sign out and if so what is the best way to do so?

@ivangarcilazo , @teckno , @mohitkhatri06 ,

Do you have any problem with clearing storage?

**Comment by mohitkhatri06** [comment]
clearing the storage is as for now is not a problem we can take care of this in future. 

apart from that @Edu58 just add this line in the package.json 

image

**Comment by Edu58** [comment]
@mohitkhatri06 
The issue on clearing the storage is clear.
I have also the missing start key in package.json

**Review by mohitkhatri06 — DISMISSED** [review]

**Review by bharathkumarchowdary — APPROVED** [review]

**Pull request merged**
