### PR TITLE
118 expenses tag creation doesnt happen when new expense is created with excel

### PR DESCRIPTION
**Pull request by ivangarcilazo**

### CODE REVIEW

**Comment by mohitkhatri06** [comment]
update and add buttons are not working,

**Comment by ivangarcilazo** [comment]
Hello Mohit! When editing I get an error but I think it's from the backend, because the payload is all the necessary information, if you could check to see if that's it.

**Comment by mohitkhatri06** [comment]
I saw that error and I guess we need to look into this piece of the code where user is constant in Expense object, we can have that user ID there its in our JWT. try that one 

image

**Comment by mohitkhatri06** [comment]
Hi Ivan so for testing purpose what I did I took one expense in the excel file (that expense tag was new only). then I tried to upload that expense sheet, the Tag was successfully created but expense didn't, you can try I will share you more details in teams

**Comment by ivangarcilazo** [comment]
I got it!

**Comment by mohitkhatri06** [comment]
until we refresh after adding the expense it render like this

image

**Comment by ivangarcilazo** [comment]
Mohit! I have detected two errors, I understand that one comes from the backend, which are different arrays that return, here I leave you some images. In the first image is what the backend returns when we create for the first time an expense, and the second is what the backend returns after reloading the page. The second is what should be returned even the first time we create the expense, otherwise, errors occur because the information that is returned is different in different actions. This was also a problem that occurred in other parts of the application, that there were different data from the backend, this generates that, for example, if I don't have expenses, I create one, and I try to edit it without reloading the page, it throws an error.


backend-error

backend-to-solve

**Comment by ivangarcilazo** [comment]
And another error I found is that when editing an expensa, if we close the modal without hitting update, the data remains, and when we open a new expensa to add it, we see the data of the expensa we were editing instead of being clean inputs.

I can raise the problem about this.

**Comment by mohitkhatri06** [comment]
> Mohit! I have detected two errors, I understand that one comes from the backend, which are different arrays that return, here I leave you some images. In the first image is what the backend returns when we create for the first time an expense, and the second is what the backend returns after reloading the page. The second is what should be returned even the first time we create the expense, otherwise, errors occur because the information that is returned is different in different actions. This was also a problem that occurred in other parts of the application, that there were different data from the backend, this generates that, for example, if I don't have expenses, I create one, and I try to edit it without reloading the page, it throws an error.
> 
> backend-error
> 
> backend-to-solve

Ivan I tried to replicate this and what I think as 1st image is getting the data from the expense create response POST(201) and the other one is from the expense GET(200), 

and usually after 201 status  we make a GET request to load latest fetched data, do we have that in the following code?

**Comment by mohitkhatri06** [comment]
> And another error I found is that when editing an expensa, if we close the modal without hitting update, the data remains, and when we open a new expensa to add it, we see the data of the expensa we were editing instead of being clean inputs.
> 
> I can raise the problem about this.

yes create a issue for the following

**Review by mohitkhatri06 — APPROVED** [review]

**Comment by ivangarcilazo** [comment]
Perfect, I'll make a problem out of it, I'll self-assign it.

And about the backend response, could you tell me more about 'do we have that in the following code?'

**Comment by mohitkhatri06** [comment]
> Perfect, I'll make a problem out of it, I'll self-assign it.
> 
> And about the backend response, could you tell me more about 'do we have that in the following code?'

probably no, what's your opinion about it, I think it is something which need to fix at frontend, the backend is working as expected.

**Pull request merged**
