### PR TITLE
Functionality for creating Financial Goals.

### PR DESCRIPTION
**Pull request by pranatiyanamandra**
This pull request includes a Goals page, which allows users to create, edit, delete and view goals.

### CODE REVIEW

**Comment by mohitkhatri06** [comment]
1. after deleting an entry list should be updated as for now that entry is visible after for until next action performed.
2.  delete 1st row then after that try to edit the proceeding rows, they are mismatching,
3.  use unicode for rupee sign 
4.  while updating a record, the dates are set to current date instead of the previous.

**Comment by mohitkhatri06** [comment]
After deleting any top row when we click on edit of next


https://github.com/GVR-Secure-Solutions/lekkalu-frontend/assets/78607953/514c5896-77ec-4363-b324-b793ecdfc1fa

**Comment by mohitkhatri06** [comment]
I added a new record, the balance is sometimes different from expected

image

**Comment by mohitkhatri06** [comment]
toFixed(2) for balance or wherever we are using decimals

image

**Comment by mohitkhatri06** [comment]
image
 Here planned finished date is showing invalid and the value of the balance is NaN

**Comment by ivangarcilazo** [comment]
CRUD on goals are make

**Comment by mohitkhatri06** [comment]
Hi Ivan getting the following error:
image

**Comment by mohitkhatri06** [comment]
Hi @ivangarcilazo please remove the subGoal field from the form.

**Review by mohitkhatri06 — APPROVED** [review]

**Review by ivangarcilazo — APPROVED** [review]

**Review by mohitkhatri06 — APPROVED** [review]

**Pull request merged**
