### PR TITLE
fix: bugs on the budget chart and added months filter

### PR DESCRIPTION
**Pull request by mohitkhatri06**
- [x] Fixed to 2 decimal
- [x] NaN is removed
- [x] filter for the last month/year added

image

### CODE REVIEW

**Comment by bharathkumarchowdary** [comment]
Better to use 3 letter notation Jan, Feb, Mar, Apr etc

**Review by bharathkumarchowdary — CHANGES_REQUESTED** [review]
- [ ] Good to have + button in budget list of dashboard to add a budget there itself
- [ ] When setting a budget, I'm seeing a calendar selector. But we should limit the user to select only year and month, not a date
- [x] List of budgets in view all of expense page must be shown in order
image

- [ ] Expense charts must be visible in Expense page
- [ ] Expenses can go higher than set budget. The scale shown in budgets widget in dashboard is maxing out at the set budget level. Some kind of representation for out of budget is required
- [ ] Within the widget if I click on any month or it's bar, it is good to have a UI element to allow me to edit or delete
- [ ] It is suggestible to have option like 3M, 6M, 1Y clickable buttons/tabs instead of dropdown "last  6 months", "last 3 months" etc. For reference check Zerodha stock chart span selection for the same

**Comment by bharathkumarchowdary** [comment]
Will be continued in 
https://github.com/GVR-Secure-Solutions/lekkalu-frontend/pull/460

**Comment by mohitkhatri06** [comment]
https://github.com/GVR-Secure-Solutions/lekkalu-frontend/pull/460

**Pull request closed without merging**
