### PR TITLE
new design for the authentication page

### PR DESCRIPTION
**Pull request by Rabbok**
---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205524174026110

### CODE REVIEW

**Comment by Rabbok** [comment]
I've redesigned the signin and signup pages and I'm ready for a review. I'd appreciate feedback, and if any changes are needed, please let me know.

**Comment by mohitkhatri06** [comment]
Hi Maksym, this design is looking big, we can reduce bit padding or margin to make it look little bit small, like width of text boxes,
The below is 80% zoom out screen, it looks fine in that, so you can take this as prototype, and adjust font size according to your experience,
image

**Comment by Rabbok** [comment]
I made the page dimensions a bit smaller. Your feedback is appreciated

**Comment by mohitkhatri06** [comment]
1. lets keep that text box same as login don't resize
2, 3.  slightly increase font size

image

**Comment by Rabbok** [comment]
I've made the changes, you can check now

**Comment by mohitkhatri06** [comment]
@Rabbok looks very good,

**Review by mohitkhatri06 — APPROVED** [review]

**Review by ivangarcilazo — APPROVED** [review]
Looks good! 🌟

**Pull request merged**
