### PR TITLE
Feature/email verification

### PR DESCRIPTION
**Pull request by HitDoshi**
What I have done in this PR-

1. When users exist but haven't verified their email, they are redirected to the email verification page.
2. Upon reopening the browser, users find their data intact, making it easy for them to recognize their existing account without needing to sign in again only email verification is needed.
3. Users can switch accounts conveniently on the verification screen.

Screenshot (939)
Screenshot (940)

### CODE REVIEW

**Comment by HitDoshi** [comment]
1. Users can view their email verification status on the profile screen. If a user's email is not verified, they can verify it by clicking on the "Verify Email" button.
2. Add a "Remind me later" feature. The email verification modal will open only once, and then again after 24 hours.
3. I have removed the force for email verification.

Screenshot (946)

Screenshot (947)

**Comment by bharathkumarchowdary** [comment]
I'm seeing the following errors

Compiled with problems:
×
ERROR
[eslint] 
src/App.tsx
  Line 98:76:  Trailing spaces not allowed  no-trailing-spaces

src/hooks/use-auth.ts
  Line 77:24:  Extra semicolon  semi
  Line 87:16:  Extra semicolon  semi

src/pages/Dashboard/Dashboard.tsx
  Line 11:31:  'setData' is defined but never used      @typescript-eslint/no-unused-vars
  Line 18:19:  Block must not be padded by blank lines  padded-blocks
  Line 19:1:   Trailing spaces not allowed              no-trailing-spaces
  Line 24:45:  Trailing spaces not allowed              no-trailing-spaces

src/pages/EmailVerification/EmailVerification.tsx
  Line 51:38:  Trailing spaces not allowed  no-trailing-spaces

src/pages/Profile/Profile.tsx
  Line 16:1:  `tailwindcss/colors` import should occur before import of `../../schema/user`  import/order

src/utils/localstorage.ts
  Line 2:44:   Extra semicolon  semi
  Line 3:16:   Extra semicolon  semi
  Line 7:38:   Extra semicolon  semi
  Line 11:34:  Extra semicolon  semi
  Line 15:25:  Extra semicolon  semi

Search for the keywords to learn more about each error.

**Comment by HitDoshi** [comment]
I have fix the following ESLint errors.
Please test now..

**Comment by HitDoshi** [comment]
Again Rebase has been done. After the test, you can merge it and close this PR also.

**Pull request closed without merging**
