### PR TITLE
Fix: Depreciation by year issue in asset

### PR DESCRIPTION
**Pull request by Sandip-Z**
This PR is associated with issue #522.

### CODE REVIEW

**Review by mohitkhatri06 — COMMENTED** [review]
1. Add the toFixed(2) for all the request post and view in the scenario 
2. Make the scenario inside the comparison also clickable
image

3.  Here as you can see we have 3 categories of the scenarios so we need to show that category total at the card view outside of the scenario so I will get to know what the scenario contains for example:
image

image


4. When we are adding the assets there is one flow which I need to discuss with you so I can explain more better that flow need to change a bit

**Comment by mohitkhatri06** [comment]
@Sandip-Z for the simulate button also we had discussion right making it float or any rippling effect to get user attention lets try in this PR it self

**Comment by mohitkhatri06** [comment]
> 1. Add the toFixed(2) for all the request post and view in the scenario
> 2. Make the scenario inside the comparison also clickable
>    image
> 3. Here as you can see we have 3 categories of the scenarios so we need to show that category total at the card view outside of the scenario so I will get to know what the scenario contains for example:
>    image
> 
> image
> 
> 4. When we are adding the assets there is one flow which I need to discuss with you so I can explain more better that flow need to change a bit

1 and 3rd point still need to work on,

make the simulate button  at the bottom right

**Comment by Sandip-Z** [comment]
@mohitkhatri06 Placing the button on bottom right interferes with the graph and looks messy. Should i do it anyways?  
Screenshot 2024-05-06 at 7 00 08 PM

**Comment by mohitkhatri06** [comment]
@Sandip-Z  lets resolve the conflicts so I can review after that

**Comment by mohitkhatri06** [comment]
@Sandip-Z please rebase this branch and resolve conflicts so we can proceed with the changes

**Comment by mohitkhatri06** [comment]
image
here 2 simulate button are coming.

**Review by mohitkhatri06 — DISMISSED** [review]

**Review by bharathkumarchowdary — APPROVED** [review]

**Comment by bharathkumarchowdary** [comment]
@Sandip-Z , there are conflicts on this PR. Please have  alook!

**Review by bharathkumarchowdary — DISMISSED** [review]

**Review by bharathkumarchowdary — DISMISSED** [review]

**Review by bharathkumarchowdary — APPROVED** [review]

**Pull request merged**
