### PR TITLE
Social login with login form

### PR DESCRIPTION
**Pull request by teckno**
-Google
-Facebook
-Apple

### CODE REVIEW

**Review by Edu58 — APPROVED** [review]

**Comment by mohitkhatri06** [comment]
@teckno  is there any other argument I need to add at command "npm install" for node_modules. I am getting following error.
image

**Comment by teckno** [comment]
> @teckno is there any other argument I need to add at command "npm install" for node_modules. I am getting following error. image

- npm install react-google-login,
- npm install react-facebook-login,
- npm install react-apple-login,

**You may need to add --force at the end depending on the package**

Such as

npm install react-google-login --force,

If need arises i can push the package.json file that am using to make things easier.

**Comment by bharathkumarchowdary** [comment]
> > @teckno is there any other argument I need to add at command "npm install" for node_modules. I am getting following error. image
> 
> * npm install react-google-login,
> * npm install react-facebook-login,
> * npm install react-apple-login,
> 
> **You may need to add --force at the end depending on the package**
> 
> Such as
> 
> * npm install react-google-login --force,
> 
> If need arises i can push the package.json file that am using to make things easier.

@teckno ,
I think it's better to push all the code for testing and reviewing purpose..

**Comment by teckno** [comment]
I recreated another Pull request

**Pull request closed without merging**
