### PR TITLE
Created Hero page. issue #184.

### PR DESCRIPTION
**Pull request by Rabbok**
In this PR, I added a new "Hero" page along with the following components:
- `HeroHeader`,
- `HeroContainer`,
- `HeroDescription`,
- Added images to the `images` folder for use on the Hero page.

### Related Issue

- [Issue #184](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/issues/184)

---
- To see the specific tasks where the Asana app for GitHub is being used, see below:
  - https://app.asana.com/0/0/1205517400102799

### CODE REVIEW

**Comment by mohitkhatri06** [comment]
let us know when the PR is ready for review.

**Comment by Rabbok** [comment]
I've completed the hero page design and it's ready for review. I'd appreciate your feedback, and if any changes are needed, please let me know.

Thanks in advance!

**Comment by mohitkhatri06** [comment]
1. as for now Hero page is in route "/hero" , Make Hero page as landing page of the site, based on the condition, if user is not logged in then we will show them Hero page  at "/". other wise redirect to the "/dashboard" or something.
2.  when click on the get started then it should take the user to the signup
3.  Less responsive when we reduce the screen size,
image

**Comment by Rabbok** [comment]
I've tried to fix it and am ready for a review. Your feedback is appreciated.

**Comment by mohitkhatri06** [comment]
I think if user is logged in and type "http://localhost:3000/" at address bar then he/she should redirected to home page   instead of the Hero page. what's your thought @ivangarcilazo ?

**Comment by ivangarcilazo** [comment]
yes, if the user is logged in, that path should lead to the home, not to the hero, I agree.

Have a nice day!

**Comment by Rabbok** [comment]
Hi. I've updated the RouterComponent code, so now when a user is logged in and types 'http://localhost:3000/' in the address bar, they will be automatically redirected to the '/home' page. If you have any more suggestions or comments, please let me know!

**Comment by bharathkumarchowdary** [comment]
Let's wait for Edwin's comment on this change.. 
@Edu58 , please check whether the redirections are good and in-line with our expectations
@Rabbok , Add a test for this functionality
@mohitkhatri06 , Update codeowners file to reflect the ownership of Edwin over all user auth and redirection related source code

**Comment by Rabbok** [comment]
Hi, I've added tests for the Hero page and resolved conflicts. If you have any further suggestions or comments, please let me know!

**Comment by mohitkhatri06** [comment]
@Edu58  please review the following PR as we are redirecting the user according to their login status

**Review by mohitkhatri06 — APPROVED** [review]

**Review by bharathkumarchowdary — APPROVED** [review]

**Comment by mohitkhatri06** [comment]
@ivangarcilazo  give a review in the following

**Review by ivangarcilazo — APPROVED** [review]

**Review by mohitkhatri06 — APPROVED** [review]

**Review by mohitkhatri06 — APPROVED** [review]

**Review by ivangarcilazo — APPROVED** [review]

**Review by bharathkumarchowdary — APPROVED** [review]

**Pull request merged**
