### PR TITLE
Feature/goals v2

### PR DESCRIPTION
**Pull request by rockingrohit9639**

### CODE REVIEW

**Comment by mohitkhatri06** [comment]
getting the following error and the dropdown of source not working sometimes:
image

**Comment by rockingrohit9639** [comment]
> getting the following error and the dropdown of source not working sometimes: image

Looks like this is an issue in backend. The object you selected is not found

**Comment by Sandip-Z** [comment]
@rockingrohit9639 can you please resolve the conflict in this PR?

**Comment by mohitkhatri06** [comment]
https://github.com/GVR-Secure-Solutions/lekkalu-frontend/pull/443

**Pull request closed without merging**
