### PR TITLE
feat/Add:CAGRCalculator-page/add:ErrorHandlerSIPCalculator

### PR DESCRIPTION
**Pull request by ivangarcilazo**

### CODE REVIEW

**Comment by mohitkhatri06** [comment]
label style in these text boxes are different from the SIP calculator, 

And for user perspective after pressing the calculate button, move the result to the right, below pie chart like SIP

**Comment by mohitkhatri06** [comment]
make sure all numbers are > 0 (positive)

**Comment by ivangarcilazo** [comment]
Mohit! How it's going? Do you think it is better delete negative numbers? Isn't that good economic information? As you think best! :)

**Comment by mohitkhatri06** [comment]
Hey Ivan, So I checked with some sites for the same where we can do this kind of calculations and they did not allowed me to enter the negative values in the input box.
for example : https://www.icicidirect.com/calculators/cagr-calculator
https://groww.in/calculators/sip-calculator

**Review by mohitkhatri06 — APPROVED** [review]

**Pull request merged**
