### PR TITLE
Odoo Helpdesk LiveChat

### PR DESCRIPTION
**Pull request by HitDoshi**
What I have done:- 

1. Add Odoo widget to the web.
2. Create "Finuncle Helpdesk" channel, add channel rules, and include a welcome bot and chatbot type on Odoo.
3. If any operator is available to answer related queries, the bot will function as a chatbot; otherwise, it will operate as a live chat.
4. Change the Odoo default theme to match our website brand color.

### CODE REVIEW

**Comment by HitDoshi** [comment]
1. If operator is not available for the chat:- Auto chatbot is on

Screenshot (944)

**Comment by HitDoshi** [comment]
- If operator is on live & available for chat so user can able to live chat with him..

Screenshot (945)

**Comment by HitDoshi** [comment]
What happens when you click on that?

**Comment by bharathkumarchowdary** [comment]
The chat is working. But the home page has nothing else. Why?

**Pull request closed without merging**
