### PR TITLE
feat: added Links to social media icons on footer

### PR DESCRIPTION
**Pull request by Sandip-Z**
This PR is for issue #434, it adds social media links in footer.

### CODE REVIEW

**Review by bharathkumarchowdary — CHANGES_REQUESTED** [review]
- [ ] Links to apps should look like this image
- [ ] Please add a unit test for the functionality added

**Comment by bharathkumarchowdary** [comment]
@Sandip-Z , Please re-request the code owners for review whenever it is ready

**Comment by mohitkhatri06** [comment]
@Sandip-Z in test case expense one is failing have look into it, otherwise SocialIcons and links are working fine

**Comment by bharathkumarchowdary** [comment]
@mohitkhatri06 , I can see all tests are passing, why do you say something is failing?
image

**Comment by mohitkhatri06** [comment]
image
@bharathkumarchowdary

**Comment by Sandip-Z** [comment]
@mohitkhatri06 The error is related to some other component's test. Should i take a look at it in this PR?

**Review by bharathkumarchowdary — APPROVED** [review]

**Pull request merged**
