### PR TITLE
fix: lending page enhancement

### PR DESCRIPTION
**Pull request by imhardikdesai**
I have made following changes

- pie chart should have all small numbers combined into others category as is done in chart's legend
- Lending Account selector should close after selecting an account
- Principal Amount field label should change to "Amount" if account is not new
- Date should be pre-filled with today
- rename Choose the date to Date
- payment method must be selectable not text input

This PR is for #466 issue

### CODE REVIEW

**Review by bharathkumarchowdary — CHANGES_REQUESTED** [review]
Please sort lending accounts by balance

**Comment by bharathkumarchowdary** [comment]
Also, add one unit test-case w.r.t the functionality added through this PR

**Comment by imhardikdesai** [comment]
@bharathkumarchowdary fix following changes
- Sorted Lending accounts in table
- added summary for both charts #465 
- unit test case of lending account and transaction
- lacs and caror notation

**Comment by bharathkumarchowdary** [comment]
> @bharathkumarchowdary fix following changes
> 
> * Sorted Lending accounts in table
> * added summary for both charts [Summary to Lending page #465](https://github.com/GVR-Secure-Solutions/lekkalu-frontend/issues/465)
> * unit test case of lending account and transaction
> * lacs and caror notation

Please re-request the review once the PR is ready

**Review by bharathkumarchowdary — APPROVED** [review]

**Review by mohitkhatri06 — APPROVED** [review]

**Pull request merged**
