### PR TITLE
6 expense upload excel does not upload all expenses

### PR DESCRIPTION
**Pull request by ivangarcilazo**

### CODE REVIEW

**Comment by mohitkhatri06** [comment]
* Some calls are breaking due to the amount format. 
image

* and also if it is possible to show some loader/spinner so user gets to know that the excel data upload is in queue and after that the count of expenses which are successfully added into the list.


* as for now this is taking around 2..3 minutes is there any way to reduce it?
image

**Comment by ivangarcilazo** [comment]
Can you check it? Thanks.

**Comment by mohitkhatri06** [comment]
@ivangarcilazo lets that modal should close when the close button is clicked otherwise that loader will also disappear.

**Comment by ivangarcilazo** [comment]
Could you explain better? Thank you!

**Comment by mohitkhatri06** [comment]
So as for now whats happening, while I uploaded the excel the loader working as expected but in that time if I click outside of the modal, the modal gets close. Its better to close this modal with the buttons.

**Comment by ivangarcilazo** [comment]
Done!

**Comment by mohitkhatri06** [comment]
when I tested with reacter credentials its working great, but when I use a new user suppose Test10 and choose excel file, page breaks (attaching screen shot) but when we refresh that the excel data successfully updated on the site.

image

**Comment by ivangarcilazo** [comment]
Hi! I am trying to get it to break as well, could you provide me with a little more detail so I can try to break it on my side and be able to find the problem? What do you mean by the new user "Test 10"? Thanks!

**Comment by mohitkhatri06** [comment]
I have shared test credentials with you in teams , this user initially did not had any expenses, when you try to add expenses by excel you will be able to reproduce.

**Comment by bharathkumarchowdary** [comment]
> So as for now what's happening, while I uploaded the excel the loader working as expected but in that time if I click outside of the modal, the modal gets close. Its better to close this modal with the buttons.
> 
>  modal.mp4 
> 
> and also there are some warnings those are by our change?

Sorry for my late reply
@mohitkhatri06 , Don't you think clicking anywhere out of the dialog box, it is nice to close it? in terms of UX?

For example, if you see LinkedIn.com, after I click start a post, a dialog box opens, and if I click away, it closes
I see this in a lot of other websites.. 

What is your take on this?

**Comment by bharathkumarchowdary** [comment]
> @bharathkumarchowdary if we wants to add that then we can do one more thing. When user uploaded the excel and click outside of the modal then there should be something which should notify the user that uploading is still in progress because what I observed that as for now our system its taking few minutes for all calls to succeed and it will not show anything that all x expenses are added or not. We can also show that how many expenses added out of the x .

Yep.. that should work nice

**Review by bharathkumarchowdary — APPROVED** [review]

**Comment by mohitkhatri06** [comment]
awesome job! @ivangarcilazo , approved.

**Review by mohitkhatri06 — APPROVED** [review]

**Pull request merged**
