### PR TITLE
Feature/goals v2 with timeline

### PR DESCRIPTION
**Pull request by Sandip-Z**
Tasks in this PR

- [x] Display goal timeline data in day, week, month and year wise.
- [x] Add Goals proportionality and target date in add goal form.
- [x] Fix on track, off track and completed graph in goals page. 
- [x] Add edit and delete goal option on each goal and API call.
- [x] Error handling while add and edit goal.
- [x] Add IncomeExpense option if none is present in user's account redirect to expense page.

### CODE REVIEW

**Review by bharathkumarchowdary — CHANGES_REQUESTED** [review]
- [ ] Without any goal in user account, it shows some on track some off track etc
- [ ] When there is no IncomeExpense object in a user's account, appropriate error message with a prompt to add one should be redirected
- [ ] Only one KPI type "LiabilityPercent" is shown. There should be some more coming from backend. If the exact endpoint for it is not findable, please contact @mohitkhatri06  or Nikhil
- [ ] After create goal is pressed, there is no feedback to user whether it is successful or not. Infact, the goal is not being created at all. I checked in backend DB, it is not happening

Some of the review points I just mentioned are very basic ones for a UI Engineer to take care of

**Comment by Sandip-Z** [comment]
@bharathkumarchowdary this PR is still on progress. Thanks for the feedback. i will look at those points.

**Review by bharathkumarchowdary — CHANGES_REQUESTED** [review]
- [ ] Target can be any number. Even negative. Why do we limit it to positive?
- [ ] The date selector field stands irrelevant. I suggest if you don't see any use of it, remove
- [ ] Dropdown is not a good Idea with time span selector. 2 clicks for span selection is  not desirable. I should see all options on screen and be able to click right away to change it
- [ ] Showing ID numbers in the list above timeline graph does not make sense to user.
- [ ] Need to add target_value to chart along with timeline. A red line is a good choise
- [ ] Good to show reachable by on the card. In a creative way

**Comment by mohitkhatri06** [comment]
@Sandip-Z if i try with http://localhost:3000/goals/909  then after loading show that server message goal not found

**Review by bharathkumarchowdary — CHANGES_REQUESTED** [review]
- [ ] Goals are reached not expired
image
- [ ] In Form fields for adding goals, * already means required, you don't need to mention (Required)

**Review by bharathkumarchowdary — APPROVED** [review]

**Pull request merged**
